import {mkdtemp, readFile, rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {basename, join} from 'node:path'
import {brotliCompressSync, constants} from 'node:zlib'

import {build} from 'tsup'

const ENTRY = {handle:'src/handle.ts', load:'src/kit-load.ts', request:'src/kit-server.ts', actions:'src/actions.ts'}
// Budgets include descriptor-only option snapshots, bounded tracing admission,
// fail-open span calls, and canonical-label protection at every adapter entry.
const scenarios = [['server handle', ENTRY.handle, 10_500, 4_100], ['load/action', ENTRY.load, 8_500, 3_200], ['request/fetch', ENTRY.request, 10_000, 3_850], ['actions', ENTRY.actions, 8_200, 3_000]]
const excluded = ['node_modules/@grafana/', 'node_modules/web-vitals/', 'node_modules/zod/', 'packages/services/']
const resolveOutput = (outputs, byBase, value) => outputs[value] ? value : byBase.get(basename(value))
const collect = (root, outputs, byBase, set, dynamic) => {if (!root || set.has(root)) return;set.add(root);for (const item of outputs[root]?.imports ?? []) if (!item.external && (dynamic || item.kind !== 'dynamic-import'))collect(resolveOutput(outputs, byBase, item.path), outputs, byBase, set, dynamic)}
const sources = (set, outputs) => {const result = new Map();for (const output of set) for (const [source, detail] of Object.entries(outputs[output]?.inputs ?? {}))result.set(source, (result.get(source) ?? 0) + detail.bytesInOutput);return [...result].sort((a, b) => b[1] - a[1])}
const bytes = async(set, outputs, dir) => {let min = 0, br = 0;for (const output of set){const value = await readFile(join(dir, basename(output)));min += Math.max(value.byteLength, outputs[output].bytes);br += brotliCompressSync(value, {params:{[constants.BROTLI_PARAM_QUALITY]:11}}).byteLength} return {min, br}}
const dir = await mkdtemp(join(tmpdir(), 'ooops-svelte-size-'))
try {await build({entry:ENTRY, format:['esm'], platform:'neutral', target:'node22', external:['@ooopsstudio/core', '@ooopsstudio/core/*'], noExternal:['@ooopsstudio/sdk'], splitting:true, treeshake:true, minify:true, dts:false, sourcemap:false, clean:true, outDir:dir, metafile:true, config:false, silent:true});const outputs = JSON.parse(await readFile(join(dir, 'metafile-esm.json'), 'utf8')).outputs;const byBase = new Map(Object.keys(outputs).map((value) => [basename(value), value]));const byEntry = new Map(Object.entries(outputs).filter(([,v]) => v.entryPoint).map(([o, v]) => [v.entryPoint, o]));const results = [];for (const [name, entry, minLimit, brLimit] of scenarios){const initial = new Set(), total = new Set();collect(byEntry.get(entry), outputs, byBase, initial, false);collect(byEntry.get(entry), outputs, byBase, total, true);const contribution = sources(total, outputs);if (!contribution.some(([source]) => source === entry)) throw new Error(`${name} undercounts ${entry}`);for (const pattern of excluded) if (contribution.some(([source]) => source.includes(pattern))) throw new Error(`${name} unexpectedly includes ${pattern}`);results.push({name, minLimit, brLimit, initial:await bytes(initial, outputs, dir), total:await bytes(total, outputs, dir), chunks:total.size, contribution})}console.log('Svelte scenario size audit');for (const value of results){const pass = value.total.min <= value.minLimit && value.total.br <= value.brLimit;console.log(`${value.name} | ${(value.initial.min / 1000).toFixed(2)}/${(value.initial.br / 1000).toFixed(2)} kB initial | ${(value.total.min / 1000).toFixed(2)}/${(value.total.br / 1000).toFixed(2)} kB total | ${value.chunks} | ${pass ? 'PASS' : 'FAIL'}`);if (process.argv.includes('--details')) for (const [source, size] of value.contribution.slice(0, 12))console.log(`  ${(size / 1000).toFixed(2)} kB ${source}`)} const failed = results.filter((v) => v.total.min > v.minLimit || v.total.br > v.brLimit);if (failed.length) throw new Error(`Svelte size budgets exceeded: ${failed.map((v) => v.name).join(', ')}`)} finally {await rm(dir, {recursive:true, force:true})}
