import {mkdtemp, readFile, rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {basename, join} from 'node:path'
import {brotliCompressSync, constants as zlibConstants} from 'node:zlib'

import {build} from 'tsup'

const ENTRY = Object.freeze({root:'src/events/index.ts', development:'src/events/public/development.ts', publisher:'src/events/size-fixtures/production-publisher.ts', worker:'src/events/size-fixtures/production-worker.ts', custom:'src/events/size-fixtures/custom-core.ts', memory:'src/events/stores/memory.ts', postgres:'src/events/stores/postgres.ts', admin:'src/events/admin.ts', observability:'src/events/public/observability.ts', migration:'src/events/migrations/postgres.ts', http:'src/events/transports/http.ts', kafka:'src/events/transports/kafka.ts', nats:'src/events/transports/nats.ts'})
const SOURCE = Object.freeze({manager:'src/events/manager.ts', memory:'src/events/memory-backend.ts', postgres:'src/events/postgres-backend.ts', observability:'src/events/public/observability.ts', migration:'src/events/migrations/postgres.ts', http:'src/events/transports/http.ts', kafka:'src/events/transports/kafka.ts', nats:'src/events/transports/nats.ts'})
const budget = (name, entry, minified, brotli, totalMinified = minified, totalBrotli = brotli, requiredInitial = [], excludedInitial = []) => ({name, entry, initialMinified:minified, initialBrotli:brotli, totalMinified, totalBrotli, requiredInitial, excludedInitial})
const SCENARIOS = Object.freeze([
	budget('root registration', ENTRY.root, 12_500, 3_500, 59_000, 16_500, [ENTRY.root], [SOURCE.manager, SOURCE.memory, SOURCE.postgres, SOURCE.http, SOURCE.kafka, SOURCE.nats]),
	budget('development', ENTRY.development, 47_000, 13_000, 47_000, 13_000, [SOURCE.manager, SOURCE.memory], [SOURCE.postgres, SOURCE.http, SOURCE.kafka, SOURCE.nats]),
	budget('production publisher', ENTRY.publisher, 42_000, 11_500, 42_000, 11_500, [SOURCE.manager], [SOURCE.memory, SOURCE.postgres, SOURCE.http, SOURCE.kafka, SOURCE.nats]),
	budget('production worker', ENTRY.worker, 42_000, 11_500, 42_000, 11_500, [SOURCE.manager], [SOURCE.memory, SOURCE.postgres, SOURCE.http, SOURCE.kafka, SOURCE.nats]),
	budget('custom core', ENTRY.custom, 42_000, 11_500, 42_000, 11_500, [SOURCE.manager], [SOURCE.memory, SOURCE.postgres, SOURCE.http, SOURCE.kafka, SOURCE.nats]),
	budget('memory backend', ENTRY.memory, 8_500, 2_800, 8_500, 2_800, [SOURCE.memory], [SOURCE.manager, SOURCE.postgres]),
	budget('PostgreSQL backend', ENTRY.postgres, 15_500, 4_500, 15_500, 4_500, [SOURCE.postgres], [SOURCE.manager, SOURCE.memory, SOURCE.migration]),
	budget('admin contracts', ENTRY.admin, 1_000, 1_000),
	budget('observability', ENTRY.observability, 4_500, 1_800, 4_500, 1_800, [SOURCE.observability], [SOURCE.manager, SOURCE.memory]),
	budget('PostgreSQL migrations', ENTRY.migration, 1_200, 1_000, 1_200, 1_000, [SOURCE.migration], [SOURCE.manager, SOURCE.postgres]),
	budget('HTTP destination', ENTRY.http, 6_700, 2_600, 6_700, 2_600, [SOURCE.http], [SOURCE.manager, SOURCE.kafka, SOURCE.nats]),
	budget('Kafka destination', ENTRY.kafka, 6_800, 2_500, 6_800, 2_500, [SOURCE.kafka], [SOURCE.manager, SOURCE.http, SOURCE.nats]),
	budget('NATS destination', ENTRY.nats, 7_000, 2_500, 7_000, 2_500, [SOURCE.nats], [SOURCE.manager, SOURCE.http, SOURCE.kafka])
])
const format = (bytes) => `${(bytes / 1_000).toFixed(2)} kB`
const resolveOutput = (outputs, byBase, path) => outputs[path] ? path : byBase.get(basename(path))
function collect(root, outputs, byBase, selected, dynamic){if (!root || selected.has(root)) return;selected.add(root);for (const item of outputs[root]?.imports ?? []){if (item.external || (!dynamic && item.kind === 'dynamic-import')) continue;collect(resolveOutput(outputs, byBase, item.path), outputs, byBase, selected, dynamic)}}
function contributions(selected, outputs){const values = new Map();for (const output of selected) for (const [source, detail] of Object.entries(outputs[output]?.inputs ?? {}))values.set(source, (values.get(source) ?? 0) + detail.bytesInOutput);return [...values].map(([source, bytes]) => ({source, bytes})).sort((a, b) => b.bytes - a.bytes || a.source.localeCompare(b.source))}
async function sizes(selected, outputs, directory){let minified = 0, brotli = 0;for (const output of selected){const bytes = await readFile(join(directory, basename(output)));minified += Math.max(bytes.byteLength, outputs[output].bytes);brotli += brotliCompressSync(bytes, {params:{[zlibConstants.BROTLI_PARAM_QUALITY]:11}}).byteLength} return {minified, brotli}}
const directory = await mkdtemp(join(tmpdir(), 'ooops-events-size-'))
try {await build({entry:ENTRY, format:['esm'], platform:'node', target:'node22', external:['@ooopsstudio/core', '@ooopsstudio/core/*'], splitting:true, treeshake:true, minify:true, dts:false, sourcemap:false, clean:true, outDir:directory, metafile:true, config:false, silent:true});const metafile = JSON.parse(await readFile(join(directory, 'metafile-esm.json'), 'utf8'));const outputs = metafile.outputs;const byBase = new Map(Object.keys(outputs).map((output) => [basename(output), output]));const byEntry = new Map(Object.entries(outputs).filter(([,value]) => value.entryPoint).map(([output, value]) => [value.entryPoint, output]));const results = [];for (const scenario of SCENARIOS){const initial = new Set(), total = new Set();collect(byEntry.get(scenario.entry), outputs, byBase, initial, false);collect(byEntry.get(scenario.entry), outputs, byBase, total, true);const initialRows = contributions(initial, outputs), initialSources = new Set(initialRows.map(({source}) => source));for (const source of scenario.requiredInitial) if (!initialSources.has(source)) throw new Error(`${scenario.name} undercounts ${source}`);for (const source of scenario.excludedInitial) if (initialSources.has(source)) throw new Error(`${scenario.name} unexpectedly includes ${source}`);results.push({...scenario, initial:await sizes(initial, outputs, directory), total:await sizes(total, outputs, directory), chunks:total.size, contributions:contributions(total, outputs)})} if (process.argv.includes('--json'))console.log(JSON.stringify({results}, null, 2));else {console.log('Events scenario/metafile audit (workspace dependencies external)');console.log('Scenario | Initial min/Br | Total min/Br | Chunks');for (const result of results){console.log(`${result.name} | ${format(result.initial.minified)}/${format(result.initial.brotli)} | ${format(result.total.minified)}/${format(result.total.brotli)} | ${result.chunks}`);if (process.argv.includes('--details')) for (const row of result.contributions.slice(0, 12))console.log(`  ${format(row.bytes)}  ${row.source}`)}} const failed = results.filter((r) => r.initial.minified > r.initialMinified || r.initial.brotli > r.initialBrotli || r.total.minified > r.totalMinified || r.total.brotli > r.totalBrotli);if (failed.length) throw new Error(`Events size budgets exceeded: ${failed.map((r) => r.name).join(', ')}`)} finally {await rm(directory, {recursive:true, force:true})}
