import {defineConfig} from 'tsup'

export default defineConfig({
	entry: {
		index: 'src/index.ts',
		'runtime/index': 'src/runtime/index.ts',
		'runtime/async/with-timeout': 'src/runtime/async/with-timeout.ts',
		'runtime/async/safe-abort-controller': 'src/runtime/async/safe-abort-controller.ts',
		'runtime/async/native-promise': 'src/runtime/async/native-promise.ts',
		'runtime/collections/native-collections': 'src/runtime/collections/native-collections.ts',
		'runtime/concurrency': 'src/runtime/concurrency/index.ts',
		'runtime/container': 'src/runtime/container.ts',
		'runtime/context': 'src/runtime/context/index.ts',
		'runtime/context/als': 'src/runtime/context/als.ts',
		'runtime/context/async-context': 'src/runtime/context/async-context.ts',
		'runtime/tracing': 'src/runtime/tracing/index.ts',
		'runtime/tracing/export-otlp': 'src/runtime/tracing/export-otlp.ts',
		'runtime/pipeline': 'src/runtime/pipeline/index.ts',
		'runtime/pipeline/batch-retry': 'src/runtime/pipeline/batch-retry.ts',
		'runtime/rate': 'src/runtime/rate/index.ts',
		'runtime/rate/token-bucket': 'src/runtime/rate/token-bucket.ts',
		'runtime/runtime/index': 'src/runtime/runtime/index.ts',
		'runtime/runtime/lifecycle-detection': 'src/runtime/runtime/lifecycle-detection.ts',
		'runtime/runtime/service-error-reporter': 'src/runtime/runtime/service-error-reporter.ts',
		'runtime/time': 'src/runtime/time/index.ts',
		'runtime/time/monotonic-clock': 'src/runtime/time/monotonic-clock.ts',
		'runtime/time/fixed-clock': 'src/runtime/time/fixed-clock.ts',
		'runtime/time/system-clock': 'src/runtime/time/system-clock.ts',
		'tokens/index': 'src/tokens/index.ts',
		'contracts/clock': 'src/contracts/clock.ts',
		'contracts/context': 'src/contracts/context.ts',
		'contracts/errors': 'src/contracts/errors.ts',
		'contracts/json': 'src/contracts/json.ts',
		'contracts/lifecycle': 'src/contracts/lifecycle.ts',
		'contracts/logging': 'src/contracts/logging.ts',
		'contracts/observability-shared': 'src/contracts/observability-shared.ts',
		'contracts/audit': 'src/contracts/audit.ts',
		'contracts/cache': 'src/contracts/cache.ts',
		'contracts/events': 'src/contracts/events.ts',
		'contracts/jobs': 'src/contracts/jobs.ts',
		'contracts/rate-limit': 'src/contracts/rate-limit.ts',
		'contracts/resilience': 'src/contracts/resilience.ts',
		'contracts/performance': 'src/contracts/performance.ts',
		'contracts/profiling': 'src/contracts/profiling.ts',
		'contracts/tracing': 'src/contracts/tracing.ts',
		'ports/errors': 'src/ports/errors.ts',
		'ports/audit': 'src/ports/audit.ts',
		'ports/cache': 'src/ports/cache.ts',
		'ports/events': 'src/ports/events.ts',
		'ports/jobs': 'src/ports/jobs.ts',
		'ports/ratelimit': 'src/ports/ratelimit.ts',
		'ports/resilience': 'src/ports/resilience.ts',
		'ports/lifecycle': 'src/ports/lifecycle.ts',
		'ports/logging': 'src/ports/logging.ts',
		'ports/metrics': 'src/ports/metrics.ts',
		'ports/performance': 'src/ports/performance.ts',
		'ports/profiling': 'src/ports/profiling.ts',
		'ports/tracing': 'src/ports/tracing.ts',
		'utils/index': 'src/utils/index.ts',
		'utils/async/backoff': 'src/utils/async/backoff.ts',
		'utils/byte-size': 'src/utils/byte-size.ts',
		'utils/clock': 'src/utils/clock.ts',
		'utils/error-boundary': 'src/utils/error-boundary.ts',
		'utils/error/index': 'src/utils/error/index.ts',
		'utils/error/normalize-error': 'src/utils/error/normalize-error.ts',
		'utils/guards/index': 'src/utils/guards/index.ts',
		'utils/compute-error-key': 'src/utils/compute-error-key.ts',
		'utils/hashing': 'src/utils/hashing/index.ts',
		'utils/hashing/simple-hash': 'src/utils/hashing/simple-hash.ts',
		'utils/hashing/stable-hash': 'src/utils/hashing/stable-hash.ts',
		'utils/misc': 'src/utils/misc.ts',
		'utils/self-metrics': 'src/utils/self-metrics.ts',
		'utils/public-network-address': 'src/utils/public-network-address.ts',
		'utils/serialization': 'src/utils/serialization/index.ts',
		'utils/testing/constants': 'src/utils/testing/constants.ts',
		'utils/tracing': 'src/utils/tracing/index.ts',
		'utils/tracing/ids': 'src/utils/tracing/ids.ts',
		'utils/tracing/propagation': 'src/utils/tracing/propagation.ts',
		'utils/tracing/sampling': 'src/utils/tracing/sampling.ts',
		'utils/validation': 'src/utils/validation.ts'
	},
	format: ['esm'],
	platform: 'neutral',
	target: 'node22',
	dts: {resolve: true},
	sourcemap: true,
	clean: true,
	// Public entry points that expose the same stateful runtime module must share
	// one module instance. Without splitting, context.js and its explicit
	// async-context subpath each bundled a private AsyncLocalStorage instance.
	splitting: true,
	treeshake: true,
	minify: false
})
