/** Fixed tracing preset policy values. */

export const SAMPLING_RATIO_PRODUCTION = 0.1

export const MAX_BAGGAGE_BYTES = 8_192
export const MAX_BAGGAGE_KEYS = 64

export const MAX_ATTRIBUTES_DEVELOPMENT = 128
export const MAX_EVENTS_DEVELOPMENT = 64
export const MAX_ATTR_BYTES_DEVELOPMENT = 8_000

export const MAX_ATTRIBUTES_PRODUCTION = 64
export const MAX_EVENTS_PRODUCTION = 32
export const MAX_ATTR_BYTES_PRODUCTION = 4_000

export const BATCH_MAX_SIZE_PRODUCTION = 128
export const BATCH_MAX_INTERVAL_PRODUCTION = 500
export const BATCH_MAX_BYTES_PRODUCTION = 64_000

export const RETRY_MAX_ATTEMPTS_PRODUCTION = 5
export const RETRY_BASE_DELAY_PRODUCTION = 100
export const RETRY_MULTIPLIER_PRODUCTION = 2
export const RETRY_MAX_DELAY_PRODUCTION = 10_000
export const RETRY_JITTER_PRODUCTION = 0.2
export const TOKEN_BUCKET_RATE_PRODUCTION = 500
export const TOKEN_BUCKET_BURST_PRODUCTION = 1_000
export const BREAKER_THRESHOLD_PRODUCTION = 7
export const BREAKER_HALF_OPEN_TIMEOUT_PRODUCTION = 15_000
